### ISSUE TITLE
CSVReader.cs:line 131 > adjustTradeBarsForSplits(): System.OverflowException: 'Value was either too large or too small for a Decimal.'

### ISSUE THREAD

**Issue by arnynerdtrader** [richlane/QuantTrade#1]
Hi,

First of all, very nice code. 
I was trying to test your solution, but it throws an error with the default parameters.

This happens on CSVReader.cs:line 131 > adjustTradeBarsForSplits():
System.OverflowException: 'Value was either too large or too small for a Decimal.'

What can I do to run the solution? 

Thanks!
Arny

**Comment by richlane** [comment]
Hi Arny
Thx for the kind words. So I am guessing that all you did was download the solution and try to run it. Let me try to do the same exact thing on a different Computer and I will let you know. I will also try to include instructions along with the solution. I will be in touch.

**Comment by richlane** [comment]
Arny - Can you please delete the QuantTrade source code from your local hard drive and pull down the latest branch and try again. I had to make some changes to the packages and solution files. Let me know how you make out.

**Comment by arnynerdtrader** [comment]
Hey Rich. 
Thanks for the response. I did what you asked, but still got the same error in the same line. 

I was able to correct the problem changing the lines 94-100 in CSVReader.cs:
```

Open = decimal.Parse(csv[1], NumberStyles.Any, CultureInfo.InvariantCulture),
High = decimal.Parse(csv[2], NumberStyles.Any, CultureInfo.InvariantCulture),
Low = decimal.Parse(csv[3], NumberStyles.Any, CultureInfo.InvariantCulture),
Close = decimal.Parse(csv[4], NumberStyles.Any, CultureInfo.InvariantCulture),
Volume = decimal.Parse(csv[6], NumberStyles.Any, CultureInfo.InvariantCulture),
Dividend = decimal.Parse(csv[7], NumberStyles.Any, CultureInfo.InvariantCulture),
SplitCoefficient = decimal.Parse(csv[8], NumberStyles.Any, CultureInfo.InvariantCulture),

```

See ya. Thanks.

**Comment by richlane** [comment]
Thx for the update. I will incorporate your fix into the code and check the code into the repo & close the bug.

**Comment by richlane** [comment]
Changes have been checked into the repo. Thx for the assist!
